package gui.dataEntryClerk;

import Domain.ChronicConditionsReport;

/**
 *
 * @author Asus
 */
public class ChronicConditionsGUI extends javax.swing.JFrame {

    DataEntryGUI parent;
    ChronicConditionsReport report;
    
    /**
     * Creates new form ChronicConditionsGUI
     */
    public ChronicConditionsGUI() {
        initComponents();
    }

    public ChronicConditionsGUI(DataEntryGUI parent, String PID) {
        this();
        this.parent = parent;
        this.report = null;
        lblPID.setText(PID);
    }
    
    public ChronicConditionsGUI(DataEntryGUI parent,ChronicConditionsReport report) {
        this();
        this.parent = parent;
        this.report = report;
        lblPID.setText(Integer.toString(report.getPID()));
        ckHeartDis.setSelected(report.isHeartDisease());
        ckStroke.setSelected(report.isStroke());
        ckCancer.setSelected(report.isCancer());
        ckDiabetes.setSelected(report.isDiabetes());
        ckObesity.setSelected(report.isObesity());
        ckArthritis.setSelected(report.isArthritis());
        txtOther.setText(report.getChronicConditionsCol());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ckHeartDis = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOther = new javax.swing.JTextArea();
        ckObesity = new javax.swing.JCheckBox();
        ckCancer = new javax.swing.JCheckBox();
        ckStroke = new javax.swing.JCheckBox();
        ckDiabetes = new javax.swing.JCheckBox();
        ckArthritis = new javax.swing.JCheckBox();
        btnDone = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblPID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Chronic Conditions");
        setMinimumSize(new java.awt.Dimension(422, 393));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ckHeartDis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckHeartDis.setText("Heart Disease");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Other :");

        txtOther.setColumns(20);
        txtOther.setRows(5);
        jScrollPane1.setViewportView(txtOther);

        ckObesity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckObesity.setText("Obesity");

        ckCancer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckCancer.setText("Cancer");

        ckStroke.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckStroke.setText("Stroke");

        ckDiabetes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckDiabetes.setText("Diabetes");

        ckArthritis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckArthritis.setText("Arthritis");

        btnDone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Patient ID :");

        lblPID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ckHeartDis)
                        .addComponent(ckStroke)
                        .addComponent(ckCancer)
                        .addComponent(ckDiabetes)
                        .addComponent(ckObesity)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ckArthritis)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblPID, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addGap(18, 18, 18)
                        .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblPID, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(ckHeartDis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckStroke)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckCancer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckDiabetes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckObesity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckArthritis)
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        if (report == null){
            report = new ChronicConditionsReport();
            report.setPID(Integer.parseInt(lblPID.getText()));
            report.setHeartDisease(ckHeartDis.isSelected());
            report.setStroke(ckStroke.isSelected());
            report.setCancer(ckCancer.isSelected());
            report.setDiabetes(ckDiabetes.isSelected());
            report.setObesity(ckObesity.isSelected());
            report.setArthritis(ckArthritis.isSelected());
            report.setChronicConditionsCol(txtOther.getText());
        }else{
            report.setHeartDisease(ckHeartDis.isSelected());
            report.setStroke(ckStroke.isSelected());
            report.setCancer(ckCancer.isSelected());
            report.setDiabetes(ckDiabetes.isSelected());
            report.setObesity(ckObesity.isSelected());
            report.setArthritis(ckArthritis.isSelected());
            report.setChronicConditionsCol(txtOther.getText());
        }
        parent.setEnabled(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDoneActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        parent.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (report == null){
            ckHeartDis.setSelected(false);
            ckStroke.setSelected(false);
            ckCancer.setSelected(false);
            ckDiabetes.setSelected(false);
            ckObesity.setSelected(false);
            ckArthritis.setSelected(false);
            txtOther.setText("");
        }else{
            ckHeartDis.setSelected(report.isHeartDisease());
            ckStroke.setSelected(report.isStroke());
            ckCancer.setSelected(report.isCancer());
            ckDiabetes.setSelected(report.isDiabetes());
            ckObesity.setSelected(report.isObesity());
            ckArthritis.setSelected(report.isArthritis());
            txtOther.setText(report.getChronicConditionsCol());
        }
        parent.setEnabled(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    public ChronicConditionsReport getReport(){
        return report;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChronicConditionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChronicConditionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChronicConditionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChronicConditionsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChronicConditionsGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDone;
    private javax.swing.JCheckBox ckArthritis;
    private javax.swing.JCheckBox ckCancer;
    private javax.swing.JCheckBox ckDiabetes;
    private javax.swing.JCheckBox ckHeartDis;
    private javax.swing.JCheckBox ckObesity;
    private javax.swing.JCheckBox ckStroke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPID;
    private javax.swing.JTextArea txtOther;
    // End of variables declaration//GEN-END:variables
}
