
package gui.dataEntryClerk;

import DataBase.ConnectionTimeOutException;
import DataBase.DBOperations;
import DataBase.Help;
import Domain.ChronicConditionsReport;
import Domain.MedicalReport;
import Domain.Patient;
import gui.login.LoginFace;
import java.sql.Date;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * @author Irfad Hussain
 */
public class DataEntryGUI extends javax.swing.JFrame {

    private Patient p;
    private ChronicConditionsGUI chronic;
    private boolean addChronicConditions; // to select whether update or insert chronic condition
    
    /**
     * Creates new form DataEntryClerkGUI
     */
    public DataEntryGUI() {
        initComponents();
        btnUpdatePatient.setEnabled(false);
        btnCanel.setEnabled(false);
        btnChronicConditions.setEnabled(false);
        chronic = null;
        // loasd todays date for report
        Date d = new Date(System.currentTimeMillis());
        txtReportYear.setText(Integer.toString(Help.getYear(d)));
        txtReportMonth.setText(Integer.toString(Help.getMonth(d)));
        txtReportDay.setText(Integer.toString(Help.getDay(d)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtReportPID = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtReportDID = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtReportDay = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtReportMonth = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtReportYear = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTreatmentDescription = new javax.swing.JTextArea();
        btnAddReport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPID = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtFullName1 = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        txtAddress1 = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        txtPatientContactNo = new javax.swing.JTextField();
        txtNameOfGuardian = new javax.swing.JTextField();
        txtGuardianContact = new javax.swing.JTextField();
        txtAllergies1 = new javax.swing.JTextField();
        cmbxGender = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtMonth = new javax.swing.JTextField();
        txtDay = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtFullName2 = new javax.swing.JTextField();
        txtAddress2 = new javax.swing.JTextField();
        txtAddress3 = new javax.swing.JTextField();
        txtAllergies2 = new javax.swing.JTextField();
        btnUpdatePatient = new javax.swing.JButton();
        btnCanel = new javax.swing.JButton();
        btnLoadPatient = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cmbxBloodGroup = new javax.swing.JComboBox();
        btnChronicConditions = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Data Entry");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/login/Secound1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Patient ID :");

        txtReportPID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtReportPID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReportPIDKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Doctor ID :");

        txtReportDID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtReportDID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReportDIDKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Date :");

        txtReportDay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtReportDay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReportDayKeyTyped(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("DD");

        txtReportMonth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtReportMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReportMonthKeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("MM");

        txtReportYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtReportYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReportYearKeyTyped(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("YYYY");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Treatment Details :");

        txtTreatmentDescription.setColumns(20);
        txtTreatmentDescription.setRows(5);
        jScrollPane2.setViewportView(txtTreatmentDescription);

        btnAddReport.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddReport.setText("Add Report");
        btnAddReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtReportPID, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtReportDID, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReportYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReportMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReportDay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel24))
                        .addGap(0, 197, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddReport)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtReportPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtReportDID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtReportYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22)
                    .addComponent(txtReportMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReportDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddReport, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add Medical report", jPanel2);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Patient ID :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("First Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Last Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Full Name :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Date of Birth :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Gender :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Address :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("NIC :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Patient Contact No :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Name of Guardian :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Guardian Contact No :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Blood Group :");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Allergies :");

        txtPID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPIDActionPerformed(evt);
            }
        });
        txtPID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPIDKeyTyped(evt);
            }
        });

        txtFirstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtLastName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtFullName1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtYear.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtYearKeyTyped(evt);
            }
        });

        txtAddress1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtNIC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNICKeyTyped(evt);
            }
        });

        txtPatientContactNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPatientContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPatientContactNoKeyTyped(evt);
            }
        });

        txtNameOfGuardian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtGuardianContact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtGuardianContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGuardianContactKeyTyped(evt);
            }
        });

        txtAllergies1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cmbxGender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbxGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("YYYY");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("MM");

        txtMonth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMonthKeyTyped(evt);
            }
        });

        txtDay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDayKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("DD");

        txtFullName2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtAddress2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtAddress3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtAllergies2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnUpdatePatient.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnUpdatePatient.setText("Update Details");
        btnUpdatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePatientActionPerformed(evt);
            }
        });

        btnCanel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCanel.setText("Cancel");
        btnCanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanelActionPerformed(evt);
            }
        });

        btnLoadPatient.setText("Load Patient");
        btnLoadPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadPatientActionPerformed(evt);
            }
        });

        cmbxBloodGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        cmbxBloodGroup.setSelectedIndex(-1);

        btnChronicConditions.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnChronicConditions.setText("Chronic Conditions ...");
        btnChronicConditions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChronicConditionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAllergies2)
                                        .addComponent(txtAllergies1)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtGuardianContact, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cmbxBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addComponent(btnCanel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnUpdatePatient))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addGap(14, 14, 14)
                                            .addComponent(jLabel10)
                                            .addGap(11, 11, 11))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                            .addGap(7, 7, 7)
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNameOfGuardian)
                                        .addComponent(txtPatientContactNo)
                                        .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAddress1)
                                        .addComponent(txtAddress2)
                                        .addComponent(txtAddress3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(btnChronicConditions, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPID, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnLoadPatient, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFullName1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(txtFullName2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoadPatient))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFullName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFullName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAddress3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPatientContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNameOfGuardian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtGuardianContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbxBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtAllergies1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAllergies2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChronicConditions, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCanel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdatePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel6);

        jTabbedPane1.addTab("Update Patient Details", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePatientActionPerformed
        // update patient if coorect details are entered. similar to add patient action performed in add patient frame
        if (validateDetails()) {
            try {
                p.setFirstName(txtFirstName.getText());
                p.setLastName(txtLastName.getText());
                p.setFullName(txtFullName1.getText() + " " + txtFullName2.getText());
                if (!txtYear.getText().equals("") || !txtMonth.getText().equals("") || !txtDay.getText().equals("")) {
                    try{
                        Date d = Help.getDate(Integer.parseInt(txtYear.getText()), Integer.parseInt(txtMonth.getText()), Integer.parseInt(txtDay.getText()));
                        if (d!=null)
                            p.setDateOfBirth(d);
                        else{
                            JOptionPane.showMessageDialog(this, "Invalid Date of Birth!", "Invalid detail", JOptionPane.WARNING_MESSAGE);
                            return;
                        }
                    }catch(NumberFormatException ex){
                        JOptionPane.showMessageDialog(this, "Invalid date of birth!", "Invalid detail", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
                p.setGender(cmbxGender.getSelectedItem().toString().substring(0, 1));
                p.setAddress(txtAddress1.getText() + " " + txtAddress2.getText() + " " + txtAddress3.getText());
                if (txtNIC.getText().equals("")) {
                    p.setNIC(null);
                } else {
                    p.setNIC(txtNIC.getText());
                }
                if (!txtPatientContactNo.getText().equals("")) {
                    try {
                        p.setPatientContactNo(Integer.parseInt(txtPatientContactNo.getText()));
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(this, "Invalid Patient Contact number!", "Invalid detail", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
                p.setNameOfTheGuardian(txtNameOfGuardian.getText());
                if (!txtGuardianContact.getText().equals("")) {
                    try {
                        p.setGuardianContactNo(Integer.parseInt(txtGuardianContact.getText()));
                    } catch (NumberFormatException ex) {
                        JOptionPane.showMessageDialog(this, "Invalid guardian contact number.", "Invalid detail", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
                if (cmbxBloodGroup.getSelectedIndex()>0){
                    p.setBloodGroup(cmbxBloodGroup.getSelectedItem().toString());
                }else{
                    p.setBloodGroup("");
                }
                p.setAllergies(txtAllergies1.getText() + " " + txtAllergies2.getText());
                DBOperations.getInstace().updatePatient(p);
                if (chronic != null){
                    if (addChronicConditions) {
                        DBOperations.getInstace().addChronicConditionsReport(chronic.getReport());
                    } else {
                        DBOperations.getInstace().updateChronicConditionsReport(chronic.getReport());
                    }
                }
                JOptionPane.showMessageDialog(this, "Successfully updated patient.", "Success", JOptionPane.INFORMATION_MESSAGE);
                btnCanelActionPerformed(null);  // preapare for next entry
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "An error occured while updating.", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (ConnectionTimeOutException ex) {
                JOptionPane.showMessageDialog(this, "Cannot update. Connection Timed out. Please try again.", "Time out", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnUpdatePatientActionPerformed

    private void btnCanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanelActionPerformed
        // clear every field, enable patient id field for editing
        txtPID.setText("");
        txtPID.setEditable(true);
        txtFirstName.setText("");
        txtLastName.setText("");
        txtFullName1.setText("");
        txtFullName2.setText("");
        txtYear.setText("");
        txtMonth.setText("");
        txtDay.setText("");
        cmbxGender.setSelectedIndex(0);
        txtAddress1.setText("");
        txtAddress2.setText("");
        txtAddress3.setText("");
        txtNIC.setText("");
        txtPatientContactNo.setText("");
        txtNameOfGuardian.setText("");
        txtGuardianContact.setText("");
        cmbxBloodGroup.setSelectedIndex(-1);
        txtAllergies1.setText("");
        txtAllergies2.setText("");
        btnUpdatePatient.setEnabled(false);
        btnCanel.setEnabled(false);
        btnChronicConditions.setEnabled(false);
        chronic = null;
    }//GEN-LAST:event_btnCanelActionPerformed

    private void btnAddReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddReportActionPerformed
        MedicalReport mReport = null;
        try{
            if (DBOperations.getInstace().checkPID(txtReportPID.getText()) && DBOperations.getInstace().checkDoctorID(txtReportDID.getText())){    // add details to the report object only if patient & Doctor id is available
                mReport = new MedicalReport();
                mReport.setPID(Integer.parseInt(txtReportPID.getText()));
                mReport.setDoctorID(Integer.parseInt(txtReportDID.getText()));
                Date d = Help.getDate(Integer.parseInt(txtReportYear.getText()), Integer.parseInt(txtReportMonth.getText()), Integer.parseInt(txtReportDay.getText()));
                if (d==null){
                    JOptionPane.showMessageDialog(this, "Invalid Date of Birth!", "Invalid detail", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                mReport.setDate(d);
                mReport.setTreatementDescription(txtTreatmentDescription.getText());
            }
        }catch(NumberFormatException ex){
            mReport = null;
            JOptionPane.showMessageDialog(this, "Invalid Date or ID!", "Invalid detail", JOptionPane.WARNING_MESSAGE);
        } catch (ConnectionTimeOutException ex) {
            mReport = null;
            JOptionPane.showMessageDialog(this, "Cannot check patient ID. Connection Timed out. Please try again.", "Time out", JOptionPane.WARNING_MESSAGE);
        }
        // report object will not be null if above operation done correctly.
        if (mReport != null){
            try {
                DBOperations.getInstace().addMedicalReport(mReport);
                JOptionPane.showMessageDialog(this, "Report added successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                // clear fields and load today's date for new report
                txtReportPID.setText("");
                txtReportDID.setText("");
                Date d = new Date(System.currentTimeMillis());
                txtReportYear.setText(Integer.toString(Help.getYear(d)));
                txtReportMonth.setText(Integer.toString(Help.getMonth(d)));
                txtReportDay.setText(Integer.toString(Help.getDay(d)));
                txtTreatmentDescription.setText("");
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Invalid Detail", null, JOptionPane.WARNING_MESSAGE);
            } catch (ConnectionTimeOutException ex) {
                JOptionPane.showMessageDialog(this, "Cannot add patient. Connection Timed out. Please try again.", "Time out", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Invalid Detail", null, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAddReportActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // if log out conformed close this window and show login window
        if (JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?","Confirm Action", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            this.dispose();
            LoginFace l = new LoginFace();
            l.setLocationRelativeTo(null);
            l.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnLoadPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadPatientActionPerformed
        p = null;
        try{
            p = DBOperations.getInstace().getPatient(Integer.parseInt(txtPID.getText()));
        }catch(NumberFormatException ex){
            p = null;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Sorry, an error occured while loading patient", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } catch (ConnectionTimeOutException ex) {
            JOptionPane.showMessageDialog(this, "Cannot load patient. Connection Timed out. Please try again.", "Time out", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (p == null){
            JOptionPane.showMessageDialog(this, "Invalid Patient ID", null, JOptionPane.ERROR_MESSAGE);
        }else{
            // if p is not null laod the details in patient object to apropriate fields
            txtPID.setEditable(false);
            txtFirstName.setText(p.getFirstName());
            txtLastName.setText(p.getLastName());
            txtFullName1.setText(p.getFullName());
            if (p.getDateOfBirth()!= null){
                txtYear.setText(Integer.toString(Help.getYear(p.getDateOfBirth())));
                txtMonth.setText(Integer.toString(Help.getMonth(p.getDateOfBirth())));
                txtDay.setText(Integer.toString(Help.getDay(p.getDateOfBirth())));
            }
            if (p.getGender().equals("M")){
                cmbxGender.setSelectedIndex(0);
            }else{
                cmbxGender.setSelectedIndex(1);
            }
            txtAddress1.setText(p.getAddress());
            txtNIC.setText(p.getNIC());
            if (p.getPatientContactNo()==0){
                txtPatientContactNo.setText("");
            } else {
                txtPatientContactNo.setText(Integer.toString(p.getPatientContactNo()));
            }
            txtNameOfGuardian.setText(p.getNameOfTheGuardian());
            if (p.getGuardianContactNo()==0){
                txtGuardianContact.setText("");
            } else {
                txtGuardianContact.setText(Integer.toString(p.getGuardianContactNo()));
            }
            String bloodGroup = p.getBloodGroup();
            if (bloodGroup==null)
                bloodGroup = "";
            switch(bloodGroup){
                case "A+":
                    cmbxBloodGroup.setSelectedIndex(0); break;
                case "A-":
                    cmbxBloodGroup.setSelectedIndex(1); break;
                case "B+":
                    cmbxBloodGroup.setSelectedIndex(2); break;
                case "B-":
                    cmbxBloodGroup.setSelectedIndex(3); break;
                case "AB+":
                    cmbxBloodGroup.setSelectedIndex(4); break;
                case "AB-":
                    cmbxBloodGroup.setSelectedIndex(5); break;
                case "O+":
                    cmbxBloodGroup.setSelectedIndex(6); break;
                case "O-":
                    cmbxBloodGroup.setSelectedIndex(7); break;
                default:
                    cmbxBloodGroup.setSelectedIndex(-1);
            }
            txtAllergies1.setText(p.getAllergies());
            btnUpdatePatient.setEnabled(true);
            btnCanel.setEnabled(true);
            btnChronicConditions.setEnabled(true);
        }
    }//GEN-LAST:event_btnLoadPatientActionPerformed

    private void btnChronicConditionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChronicConditionsActionPerformed
        if (chronic == null){
            try {
                ChronicConditionsReport chronicCondition = DBOperations.getInstace().getChronicCondotionReport(p.getPID());
                if (chronicCondition != null) {
                    addChronicConditions = false;
                    chronic = new ChronicConditionsGUI(this, chronicCondition);
                    chronic.setLocationRelativeTo(null);
                    chronic.setVisible(true);
                    this.setEnabled(false);
                } else {
                    addChronicConditions = true;
                    chronic = new ChronicConditionsGUI(this, txtPID.getText());
                    chronic.setLocationRelativeTo(null);
                    chronic.setVisible(true);
                    this.setEnabled(false);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Sorry, an error occured while loading Chronic conditions", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (ConnectionTimeOutException ex) {
                JOptionPane.showMessageDialog(this, "Cannot load Chronic conditions. Connection Timed out. Please try again.", "Time out", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            chronic.setVisible(true);
        }
    }//GEN-LAST:event_btnChronicConditionsActionPerformed

    private void txtReportPIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReportPIDKeyTyped
        if (!Help.allowOnlyDigit(txtReportPID.getText(), 10, evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtReportPIDKeyTyped

    private void txtReportDIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReportDIDKeyTyped
        if (!Help.allowOnlyDigit(txtReportDID.getText(), 10, evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtReportDIDKeyTyped

    private void txtReportYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReportYearKeyTyped
        if (!Help.allowOnlyDigit(txtReportYear.getText(), 4, evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtReportYearKeyTyped

    private void txtReportMonthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReportMonthKeyTyped
        if (!Help.allowOnlyDigit(txtReportMonth.getText(), 2, evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtReportMonthKeyTyped

    private void txtReportDayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReportDayKeyTyped
        if (!Help.allowOnlyDigit(txtReportDay.getText(), 2, evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtReportDayKeyTyped

    private void txtPIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPIDKeyTyped
        if (!Help.allowOnlyDigit(txtPID.getText(), 10, evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtPIDKeyTyped

    private void txtYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyTyped
        if (!Help.allowOnlyDigit(txtYear.getText(), 4, evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtYearKeyTyped

    private void txtMonthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMonthKeyTyped
        if (!Help.allowOnlyDigit(txtMonth.getText(), 2, evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtMonthKeyTyped

    private void txtDayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDayKeyTyped
        if (!Help.allowOnlyDigit(txtDay.getText(), 2, evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtDayKeyTyped

    private void txtNICKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNICKeyTyped
        char c = evt.getKeyChar();
        if (txtNIC.getText().length()<9 && !Character.isDigit(c)){
            evt.consume();
            return;
        }
        if (txtNIC.getText().length()==9 && !(c=='v' || c=='V' || c=='x' || c=='X')){
            evt.consume();
            return;
        }
        if (txtNIC.getText().length()==10){
            evt.consume();
        }
    }//GEN-LAST:event_txtNICKeyTyped

    private void txtPatientContactNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPatientContactNoKeyTyped
        if (!Help.allowOnlyDigit(txtPatientContactNo.getText(), 10, evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtPatientContactNoKeyTyped

    private void txtGuardianContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGuardianContactKeyTyped
        if (!Help.allowOnlyDigit(txtGuardianContact.getText(), 10, evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtGuardianContactKeyTyped

    private void txtPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPIDActionPerformed
        btnLoadPatientActionPerformed(null);
    }//GEN-LAST:event_txtPIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new DataEntryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddReport;
    private javax.swing.JButton btnCanel;
    private javax.swing.JButton btnChronicConditions;
    private javax.swing.JButton btnLoadPatient;
    private javax.swing.JButton btnUpdatePatient;
    private javax.swing.JComboBox cmbxBloodGroup;
    private javax.swing.JComboBox cmbxGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtAddress1;
    private javax.swing.JTextField txtAddress2;
    private javax.swing.JTextField txtAddress3;
    private javax.swing.JTextField txtAllergies1;
    private javax.swing.JTextField txtAllergies2;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtFullName1;
    private javax.swing.JTextField txtFullName2;
    private javax.swing.JTextField txtGuardianContact;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtNameOfGuardian;
    private javax.swing.JTextField txtPID;
    private javax.swing.JTextField txtPatientContactNo;
    private javax.swing.JTextField txtReportDID;
    private javax.swing.JTextField txtReportDay;
    private javax.swing.JTextField txtReportMonth;
    private javax.swing.JTextField txtReportPID;
    private javax.swing.JTextField txtReportYear;
    private javax.swing.JTextArea txtTreatmentDescription;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

    private boolean validateDetails() {
        if (txtFirstName.getText().equals("")){
            JOptionPane.showMessageDialog(this, "First Name cannot be empty!", "Invalid Detail", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (txtFullName1.getText().equals("") && txtFullName2.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Full Name cannot be empty!", "Invalid Detail", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        String NIC = txtNIC.getText();
        if (!NIC.equals("") && !(NIC.length()==10 && (NIC.substring(NIC.length()-1, NIC.length()).equalsIgnoreCase("V") || NIC.substring(NIC.length()-1, NIC.length()).equalsIgnoreCase("V")))){
            JOptionPane.showMessageDialog(this, "Invalid NIC","Invalid Detail", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        try {
            if (!NIC.equals(""))
                Integer.parseInt(NIC.substring(0, NIC.length() - 1)); // first 9 digits should be numbers
            if (p.getNIC()==null && DBOperations.getInstace().checkPatientNIC(NIC)){  // check NIC available in database only if it is not entered previously for this patient
                JOptionPane.showMessageDialog(this, "NIC already exsits","Invalid Detail", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Invalid NIC", "Invalid Detail", JOptionPane.WARNING_MESSAGE);
            return false;
        } catch (ConnectionTimeOutException ex) {
            JOptionPane.showMessageDialog(this, "Cannot check NIC. Connection Timed out. Please try again.", "Time out", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        return true;
    }
}
